source: docs
destination: _site
name: WordPress for Publishers
url: https://wpforpublishers.com
repository: kasparsd/wp-for-publishers

collections:
  guidebook:
    output: true
    permalink: /:name.html

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      weight: 10
